### ISSUE TITLE
StorageFile is not compatible with IStorageFile in winrt-uwp

### ISSUE THREAD

**Issue by RReverser** [SaschaNaz/uwp-type-generator#4]
With `winrt-uwp`, getting following error whenever `StorageFile` is being passed/assigned to variable of expected `IStorageFile` type (which should be compatible by design):

```
error TS2345: Argument of type 'StorageFile' is not assignable to parameter of type 'IStorageFile'.
  Types of property 'copyAndReplaceAsync' are incompatible.
    Type '(fileToReplace: IStorageFile) => IPromiseWithOperation<void, IAsyncAction>' is not assignable to type '(fileToReplace: IStorageFile) => IAsyncAction'.
      Type 'IPromiseWithOperation<void, IAsyncAction>' is not assignable to type 'IAsyncAction'.
        Property 'getResults' is missing in type 'IPromiseWithOperation<void, IAsyncAction>'.
```

It works well in pure `winrt` definitions, but on the other hand they don't contain some of the new APIs, so neither works perfectly.

Maybe it's worth to consider generating `winrt-uwp` which just extends `winrt` with new APIs instead of duplicating them? (as an example, `chrome/chrome-app` definitions do this to `chrome/chrome`)

**Comment by saschanaz** [comment]
I'll look into this. 

> Maybe it's worth to consider generating  winrt-uwp  which just extends  winrt  with new APIs instead of duplicating them?

That will be great if possible but the original winrt.d.ts is written by hand so I cannot easily know whether there is a missing type or not. It also has some typing bugs, so I just duplicated them.

**Comment by saschanaz** [comment]
a86170b25d7604f5bd69c1a2256d70f756e003ef should fix this. Thanks!

**Comment by RReverser** [comment]
> That will be great if possible but the original winrt.d.ts is written by hand so I cannot easily know whether there is a missing type or not.

TypeScript parser & AST traversal could probably help with it.

**Comment by RReverser** [comment]
And thanks for a quick fix, I'll try it.

**Comment by RReverser** [comment]
Yes, it helped. Could you please publish update to TSD?

**Comment by saschanaz** [comment]
> TypeScript parser & AST traversal could probably help with it.

Definitely, if I was good at using TypeScript parser API... A help will be appreciated.

**Comment by saschanaz** [comment]
I filed a new issue #5 for AST traversal and I will soon publish to TSD after I fix some other bugs.
