### ISSUE TITLE
Merge ISomeInterface{2,3,...} into ISomeInterface

### ISSUE THREAD

**Issue by RReverser** [SaschaNaz/uwp-type-generator#7]
Those interfaces are available in C# and Windows.Storage.Storage{File,Folder} classes implement them, but in winrt-uwp.d.ts their definitions are missing.

Not sure whether we really want them as separate interfaces or just extend existing ones (since we don't care about actual C# parity), but would be nice to have them in any form.

**Comment by saschanaz** [comment]
Currently I only add interfaces that referenced by other WinRT methods or properties at least once, but IStorage{*}2 is never referenced by other. Do you have some specific use cases?

**Comment by RReverser** [comment]
I'm writing functions that can accept any StorageItem and tried to use `.getParentAsync`, and that beats me as I have to define

``` typescript
type IStorageItem = Windows.Storage.StorageFile | Windows.Storage.StorageFolder;
```

which kind of works, but is just an ugly hack :(

As for references - are not those interfaces implemented (and thus referenced) by Windows.Storage.Storage{File,Folder} classes as mentioned above or it doesn't count?

**Comment by saschanaz** [comment]
Class implementation is not counted as it is not required to express a class, whose document already has all member descriptions required.

BTW, `winrt.d.ts` already have `Windows.Storage.IStorageItem`. Are there some reasons you cannot use it?

**Comment by RReverser** [comment]
That's the issue - `IStorageItem` doesn't contain new methods such as `getParentAsync` and others.

**Comment by saschanaz** [comment]
I see the pain. However, adding `IStorageItem2` will still require `type IStorageItemWhatever = Windows.Storage.IStorageItem & Windows.Storage.IStorageItem2`. Hmm...

**Comment by RReverser** [comment]
Yeah, that's why I said

> or just extend existing ones (since we don't care about actual C# parity)

I believe that shouldn't harm anyone, and at the same time would provide access to the latest methods.

**Comment by RReverser** [comment]
Since this is a common pattern, I think it shouldn't be hard to change behavior of generator to merge any `ISomeInterface{1,2,3,...}` into `ISomeInterface`.

**Comment by saschanaz** [comment]
It should be doable if we can be sure that every class that implements `ISomeInterface` also implements `ISomeInterface{1,2,3,...}`. A quick search makes me think it is but I should check them all.

**Comment by saschanaz** [comment]
It seems there is no `ISomeInterface3` for UWP yet. The change is now in master branch: https://github.com/SaschaNaz/uwp-type-generator/commit/8f2dd54fcb7b82cb79e1d13a6ee4323b8ebfd970

**Comment by RReverser** [comment]
Sure, I suggested it exclusively for future-proof implementation. Thanks, that helps!
